[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
from = "/api/*"
to = "https://backend.link-sharing-app-elfabri.netlify.app/:splat"
status = 200
force = true
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
for = "/*"
[headers.values]
  Access-Control-Allow-Origin = "http://localhost:3302"
  Access-Control-Allow-Credentials = "true"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
