[build]
  command = "npm run build"
  publish = "dist"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://link-sharing-app-elfabri.netlify.app"
    Access-Control-Allow-Credentials = "true"