[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
from = "/*"
to = "https://backend.link-sharing-app-elfabri.netlify.app/:splat"
status = 200
force = true

[[headers]]
for = "/*"
[headers.values]
  Access-Control-Allow-Origin = "http://localhost:3302"
  Access-Control-Allow-Credentials = "true"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
